/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/mesa.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mesa.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_Mesh_head_geo001_lambert2SG001.geometry} material={materials['lambert2SG.001']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/mesa.glb')
