version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_api
    ports:
      - '3333:3332'
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx # Mapeia a pasta de logs do container para o host
    ports:
      - '80:80'
    depends_on:
      - api
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
